apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: 393416881671.dkr.ecr.us-east-1.amazonaws.com/cloudpunk-sample-pythonap
        name: web
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_ID
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_ID
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_URL
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_PASS
        resources: {}
      restartPolicy: Always
status: {}
